alias g='git'
alias gcm='git checkout master'
alias gdf='git df'
alias gds='git ds'
alias gg='git grep -n'
alias gl='git lg'
alias gst='git status'
alias j='jasmine-headless-webkit'
alias r='rails'
alias rs='rake spec'
alias rsc='rake spec:controllers'
alias rsm='rake spec:models'
alias rsv='rake spec:views'

